// <auto-generated />
using AppAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AppAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180523193456_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("MessengerAPI.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("receiverID");

                    b.Property<string>("senderID");

                    b.Property<string>("text");

                    b.Property<DateTime>("timeSent");

                    b.HasKey("ID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("MessengerAPI.Models.UserContacts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ExtendedDataStr");

                    b.Property<string>("owner");

                    b.HasKey("ID");

                    b.ToTable("UserContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
